new aemdc-files structure refactoring

diff --git a/src/main/distribution-resources/bin/aemdctest b/src/main/distribution-resources/bin/aemdctest
--- a/src/main/distribution-resources/bin/aemdctest
+++ b/src/main/distribution-resources/bin/aemdctest
@@ -12,29 +12,43 @@ TESTVALID=true
 
 # define test directory
 TESTDIR="aemdctest"
+TESTPROJECT="my-test-project"
+TESTPAEMDC_FILES="aemdc-files"
 
 # delete old test directory
 if [ -d  "$TESTDIR" ] ; then
-  read -r -p "Would you like to delete test directory $TESTDIR? (y/n)" TESTDIR_DELETE
+  if [ -d  "$TESTDIR/$TESTPROJECT" ] ; then
+    read -r -p "Would you like to delete test directory $TESTDIR/$TESTPROJECT? (y/n)" TESTDIR_DELETE
 
-  if [ "y" = "$TESTDIR_DELETE" ] ; then
-    rm -rf "$TESTDIR"
-    echo "$TESTDIR deleted."
-  else
-    echo "Error: please delete test directory."
-    exit 1
+    if [ "y" = "$TESTDIR_DELETE" ] ; then
+      rm -rf "$TESTDIR/$TESTPROJECT"
+      echo "$TESTPROJECT deleted."
+    else
+      echo "Error: please delete test project."
+      exit 1
+    fi
   fi
+
+  if [ -d  "$TESTDIR/$TESTPAEMDC_FILES" ] ; then
+    read -r -p "Would you like to delete test directory $TESTDIR/$TESTPAEMDC_FILES? (y/n)" TESTDIR_DELETE
+    if [ "y" = "$TESTDIR_DELETE" ] ; then
+      rm -rf "$TESTDIR/$TESTPAEMDC_FILES"
+      echo "$TESTPAEMDC_FILES deleted."
+    fi
+  fi
+else
+  # create "aemdctest" dir
+  mkdir -p "$TESTDIR"
 fi
 
-# create "aemdctest" dir
-mkdir -p "$TESTDIR"
+# change to "aemdctest" dir
 cd "$TESTDIR"
 
 # create "my-test-project" using the Lazybones project creator.
 echo "Starting to create "my-test-project" using the Lazybones project creator..."
 lazybones create aem-multimodule-project my-test-project -PgroupId=com.headwire.myaem -PartifactId=my-test-project -PuseNewNamingConvention=yes -PbundleInBundlesDirectory=no -PbundleArtifactId=my-test-project.core -PcontentArtifactId=my-test-project.ui.apps -Pversion=1.0.0-SNAPSHOT -PprojectName="My AEM Project" -PpackageGroup=my-test-project -PaemVersion=6.2 -PappsFolderName=my-test-project -PcontentFolderName=my-test-project -PcreateEditableTemplatesStructure=yes -PconfFolderName=my-test-project -PcreateDesign=yes -PdesignFolderName=my-test-project -PcreateMainClientLib=yes -PcreateDependenciesClientLib=no -PenableCodeQuality=no -PcreateRunModeConfigFolders=no -PcreateAuthorAndPublishPerEnv=no -PreconfigureRootMapping=no -PincludeAcsAemCommons=no -PusingSlingModels=yes -PslingModelsPackage=com.headwire.myaem.core -PpurgeDamWorkflows=no
 
-cd my-test-project
+cd $TESTPROJECT
 
 # create aemdc-config.properties
 aemdc config
@@ -57,7 +71,7 @@ fi
 # create and check COMPONENT
 aemdc component contentpage page/page "jcr:title=CompContentPage"
 aemdc component component-js content/CompJS "jcr:title=CompJSTitle"
-aemdc component component-model content/hero "jcr:title=Hero Title" "comp-model=com.headwire.myaem.models.Hero"
+aemdc component component-model content/hero "jcr:title=Hero Title" "comp-model=com.headwire.myaem.models.hero.Hero"
 
 # COMPONENT check
 TARGETDIR="ui.apps/src/main/content/jcr_root/apps/my-test-project/components"
@@ -76,7 +90,7 @@ fi
 
 
 # create and check OSGI
-aemdc osgi osgi.1.PID.xml com.day.cq.mypkg.impl.MyService.xml "runmode=author.prod" "ph_1_1:mobile.resourceTypes=[my-test-project/components/medianewsletter]" "ph_1_1:README=Use these configuration settings to indicate..."
+aemdc osgi osgi.pid com.day.cq.mypkg.impl.MyService "runmode=author.prod" "ph_1_1:mobile.resourceTypes=[my-test-project/components/medianewsletter]" "ph_1_1:README=Use these configuration settings to indicate..."
 
 # OSGI check
 TARGETDIR="ui.apps/src/main/content/jcr_root/apps/my-test-project/config.author.prod"
@@ -116,8 +130,8 @@ fi
 
 
 # create and check MODEL
-aemdc model HeroModel.java hero/Hero.java
-aemdc model SampleSlingModel.java list/GraphicList.java
+aemdc model hero hero
+aemdc model sling list "java-class=GraphicList"
 
 # MODEL check
 TARGETDIR="core/src/main/java/com/headwire/myaem/core/models"
@@ -132,41 +146,48 @@ fi
 
 
 # create and check SERVICE
-aemdc service SampleService.java MySampleService.java
-aemdc service impl/SampleServiceImpl.java impl/MySampleServiceImpl.java
+aemdc service sample mysample
+aemdc service sample mysample "java-class=MySampleService"
 
 # SERVICE check
 TARGETDIR="core/src/main/java/com/headwire/myaem/core/services"
-if [ ! -f  "$TARGETDIR/MySampleService.java" ] ; then
+if [ ! -f  "$TARGETDIR/mysample/Mysample.java" ] ; then
   TESTVALID=false
-  echo "ERROR: there is no service definition in the target directory $TARGETDIR/MySampleService.java"
+  echo "ERROR: there is no service definition in the target directory $TARGETDIR/mysample/Mysample.java"
 fi
-if [ ! -f  "$TARGETDIR/impl/MySampleServiceImpl.java" ] ; then
+if [ ! -f  "$TARGETDIR/mysample/MysampleImpl.java" ] ; then
   TESTVALID=false
-  echo "ERROR: there is no service definition in the target directory $TARGETDIR/impl/MySampleServiceImpl.java"
+  echo "ERROR: there is no service definition in the target directory $TARGETDIR/mysample/MysampleImpl.java"
 fi
-
+if [ ! -f  "$TARGETDIR/mysample/MySampleService.java" ] ; then
+  TESTVALID=false
+  echo "ERROR: there is no service definition in the target directory $TARGETDIR/mysample/MySampleService.java"
+fi
+if [ ! -f  "$TARGETDIR/mysample/MySampleServiceImpl.java" ] ; then
+  TESTVALID=false
+  echo "ERROR: there is no service definition in the target directory $TARGETDIR/mysample/MySampleServiceImpl.java"
+fi
 
 # create and check SERVLET
-aemdc servlet impl/SampleSafeMethodsServlet.java MyServlet.java
-aemdc servlet impl/SampleSafeMethodsServlet.java impl/MySampleSafeMethodsServlet.java
+aemdc servlet safemethods test
+aemdc servlet safemethods safes/impl "java-class=SampleSafeMethodsServlet"
 
 # SERVLET check
 TARGETDIR="core/src/main/java/com/headwire/myaem/core/servlets"
-if [ ! -f  "$TARGETDIR/MyServlet.java" ] ; then
+if [ ! -f  "$TARGETDIR/test/Test.java" ] ; then
   TESTVALID=false
-  echo "ERROR: there is no service definition in the target directory $TARGETDIR/MyServlet.java"
+  echo "ERROR: there is no service definition in the target directory $TARGETDIR/test/Test.java"
 fi
-if [ ! -f  "$TARGETDIR/impl/MySampleSafeMethodsServlet.java" ] ; then
+if [ ! -f  "$TARGETDIR/safes/impl/SampleSafeMethodsServlet.java" ] ; then
   TESTVALID=false
-  echo "ERROR: there is no servlet definition in the target directory $TARGETDIR/impl/MySampleSafeMethodsServlet.java"
+  echo "ERROR: there is no servlet definition in the target directory $TARGETDIR/safes/impl/SampleSafeMethodsServlet.java"
 fi
 
 
 # create and check im TEMP folder
 aemdc -temp=temp/folder config
 aemdc -temp=temp/folder component contentpage page/myTempContentPage "jcr:title=CompContentPage"
-aemdc -temp=temp/folder model HeroModel.java hero/TempHero.java
+aemdc -temp=temp/folder model hero myhero "java-class=TempHero"
 
 # TEMP folder check
 TARGETDIR="temp/folder"
@@ -180,9 +201,9 @@ if [ ! -f  "$TARGETDIR/page/myTempContentPage/.content.xml" ] ; then
   echo "ERROR: there is no component definition in the target directory $TARGETDIR/page/myTempContentPage/.content.xml"
 fi
 TARGETDIR="temp/folder/core/src/main/java/com/headwire/myaem/core/models"
-if [ ! -f  "$TARGETDIR/hero/TempHero.java" ] ; then
+if [ ! -f  "$TARGETDIR/myhero/TempHero.java" ] ; then
   TESTVALID=false
-  echo "ERROR: there is no model definition in the target directory $TARGETDIR/hero/TempHero.java"
+  echo "ERROR: there is no model definition in the target directory $TARGETDIR/myhero/TempHero.java"
 fi
 
 
