shell and windows .bat scripts added

diff --git a/src/main/distribution-resources/bin/aemdc b/src/main/distribution-resources/bin/aemdc
--- a/src/main/distribution-resources/bin/aemdc
+++ b/src/main/distribution-resources/bin/aemdc
@@ -1,1 +1,133 @@
 #!/bin/sh
+#
+#----------------------------------------------------------------------------
+#AEMDC Start Up Batch script
+#
+#Required ENV vars:
+#------------------
+#  JAVA_HOME - location of a JDK home dir
+#
+#Optional ENV vars
+#-----------------
+#  AEMDC_OPTS - parameters passed to the Java VM when running AEMDC
+#    e.g. to debug AEMDC itself, use
+#      set AEMDC_OPTS=-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000
+#----------------------------------------------------------------------------
+
+if [ -f /etc/aemdcrc ] ; then
+  . /etc/aemdcrc
+fi
+
+if [ -f "$HOME/.aemdcrc" ] ; then
+  . "$HOME/.aemdcrc"
+fi
+
+# resolve links - $0 may be a softlink
+PRG="$0"
+
+while [ -h "$PRG" ]; do
+  ls=`ls -ld "$PRG"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '/.*' > /dev/null; then
+    PRG="$link"
+  else
+    PRG=`dirname "$PRG"`/"$link"
+  fi
+done
+
+PRGDIR=`dirname "$PRG"`
+AEMDC_HOME=`cd "$PRGDIR/.." >/dev/null; pwd`
+
+
+
+# OS specific support.  $var _must_ be set to either true or false.
+cygwin=false;
+darwin=false;
+case "`uname`" in
+  CYGWIN*) cygwin=true ;;
+  Darwin*) darwin=true
+           if [ -z "$JAVA_VERSION" ] ; then
+             VERSION=""
+           else
+             VERSION="-v $JAVA_VERSION"
+             echo "Using Java version: $JAVA_VERSION"
+           fi
+           if [ -z "$JAVA_HOME" ] ; then
+             JAVA_HOME=`/usr/libexec/java_home $JAVA_VERSION`
+           fi
+           ;;
+esac
+
+if [ -z "$JAVA_HOME" ] ; then
+  if [ -r /etc/gentoo-release ] ; then
+    JAVA_HOME=`java-config --jre-home`
+  fi
+fi
+
+# For Cygwin, ensure paths are in UNIX format before anything is touched
+if $cygwin ; then
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
+fi
+
+# If a specific java binary isn't specified search for the standard 'java' binary
+if [ -z "$JAVACMD" ] ; then
+  if [ -n "$JAVA_HOME"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+      # IBM's JDK on AIX uses strange locations for the executables
+      JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+      JAVACMD="$JAVA_HOME/bin/java"
+    fi
+  else
+    JAVACMD=`which java`
+  fi
+fi
+
+if [ ! -x "$JAVACMD" ] ; then
+  echo "Error: JAVA_HOME is not defined correctly." 1>&2
+  echo "  We cannot execute $JAVACMD" 1>&2
+  exit 1
+fi
+
+if [ -z "$REPO" ]
+then
+  REPO="$AEMDC_HOME"/lib
+fi
+
+# CLASSPATH=$CLASSPATH_PREFIX:"$REPO"/aemdc-1.0.0-SNAPSHOT-jar-with-dependencies.jar
+CLASSPATH=$CLASSPATH_PREFIX
+MAINJARPATH="$REPO"/aemdc-1.0.0-SNAPSHOT-jar-with-dependencies.jar
+
+# For Cygwin, switch paths to Windows format before running java
+if $cygwin; then
+  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+  [ -n "$MAINJARPATH" ] && MAINJARPATH=`cygpath --path --windows "$MAINJARPATH"`
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
+  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
+  [ -n "$AEMDC_HOME" ] && AEMDC_HOME=`cygpath --path --windows "$AEMDC_HOME"`
+  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
+fi
+
+# EXTRA_JVM_ARGUMENTS="-Xms500m -Xmx500m -XX:PermSize=128m -XX:-UseGCOverheadLimit"
+EXTRA_JVM_ARGUMENTS=""
+
+# try to determine terminal width
+COLS=$COLUMNS
+if [ -x "/bin/stty" ]; then
+    TERM_SIZE=`/bin/stty size 2>/dev/null` 
+    for a in ${TERM_SIZE}; do
+        COLS=$a
+    done
+fi
+
+if [ -n "$COLS" ]; then
+    EXTRA_JVM_ARGUMENTS="$EXTRA_JVM_ARGUMENTS -Denv.term.width=${COLS}"
+fi
+
+exec "$JAVACMD" $AEMDC_OPTS $EXTRA_JVM_ARGUMENTS \
+  -classpath "$CLASSPATH" \
+  -Dapp.name="aemdc" \
+  -Dapp.pid="$$" \
+  -jar "$MAINJARPATH" \
+  "$@"
